export default function MenuIcon({ className }: { className: string }) {
  return (
    <svg
      className={className}
      width="18"
      height="13"
      viewBox="0 0 30 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <line
        x1="1.8353"
        y1="2"
        x2="28.2122"
        y2="2"
        fill="currentColor"
        strokeWidth="3"
        strokeLinecap="round"
      />
      <line
        x1="1.8353"
        y1="12"
        x2="28.2122"
        y2="12"
        fill="currentColor"
        strokeWidth="3"
        strokeLinecap="round"
      />
      <line
        x1="1.8353"
        y1="22"
        x2="28.2122"
        y2="22"
        fill="currentColor"
        strokeWidth="3"
        strokeLinecap="round"
      />
    </svg>
  );
}
